version: '3.8'

services:
  backend:
    build: 
      context: ./Tasks_Back
      dockerfile: Dockerfile
    container_name: tasks_backend
    ports:
      - "2676:80" #main 2654,pizza 2676
    volumes:
      - ./Tasks_Back:/var/www/html
    restart: unless-stopped

  frontend:
    image: busybox:latest
    container_name: tasks_frontend
    command: httpd -f -v -p 80 -h /var/www/html
    ports:
      - "2820:80" #main 2876,pizza 2820
    volumes:
      - ./Tasks_Front/dist:/var/www/html:ro
    restart: unless-stopped

  # ----- added -----
  queue:
    build:
      context: ./Tasks_Back
      dockerfile: Dockerfile
    container_name: tasks_queue
    command: sh -lc "php artisan queue:work --queue=high,default --tries=3 --timeout=120 --sleep=1"
    volumes:
      - ./Tasks_Back:/var/www/html
    restart: unless-stopped
    depends_on:
      - backend

  # ----- added -----
  reverb:
    build:
      context: ./Tasks_Back
      dockerfile: Dockerfile
    container_name: tasks_reverb
    command: sh -lc "php artisan reverb:start --host=0.0.0.0 --port=6031"
    ports:
      - "6031:6031"   # main 6001, pizza 6031
    volumes:
      - ./Tasks_Back:/var/www/html
    restart: unless-stopped
    depends_on:
      - backend
